### ISSUE TITLE
The integration_tests don't pass

### ISSUE THREAD

**Issue by dluschan** [Michael-F-Bryan/mdbook-epub#79]
The tests don't pass:
```
cargo test
...
thread 'output_epub_is_valid' panicked at 'called `Result::unwrap()` on an `Err` value: EpubCheck', tests/integration_tests.rs:79:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
...
```

**Comment by blandger** [comment]
Even you PR run tests without errors.
https://github.com/Michael-F-Bryan/mdbook-epub/pull/80/checks
see "Run tests" section.

What is your envivonment, OS, cargo version?

**Comment by dluschan** [comment]
macOS 13.5.2, EPUBCheck v5.1.0 (from brew), cargo 1.72.0

**Comment by blandger** [comment]
Can you try to debug/dump the result of test **fn output_epub_is_valid()** locally to figure out source of the problem ?? I suspect something like missing file without permission to write disk, or something similar... not sure, but...

**Comment by dluschan** [comment]
May be this output `epubcheck DummyBook.epub` helps you:
```
ERROR(OPF-060): DummyBook.epub/./DummyBook.epub(-1,-1): Duplicate entry in the ZIP file: "OEBPS/assets/rust-logo.png" (file names must be unique after Unicode canonical normalization and full case folding).
Validating using EPUB version 2.0.1 rules.
ERROR(RSC-005): DummyBook.epub/OEBPS/content.opf(16,129): Error while parsing file: value of attribute "id" is invalid; must be an XML name without colons
ERROR(RSC-005): DummyBook.epub/OEBPS/content.opf(25,58): Error while parsing file: value of attribute "idref" is invalid; must be an XML name without colons
ERROR(RSC-005): DummyBook.epub/OEBPS/content.opf(18,89): Error while parsing file: The "id" attribute does not have a unique value
ERROR(RSC-005): DummyBook.epub/OEBPS/content.opf(21,89): Error while parsing file: The "id" attribute does not have a unique value
ERROR(RSC-005): DummyBook.epub/OEBPS/chapter_1.html(18,87): Error while parsing file: element "img" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")
ERROR(RSC-007): DummyBook.epub/OEBPS/chapter_1.html(15,74): Referenced resource "third_party/wikimedia/Epub_logo_color.svg" could not be found in the EPUB.

Check finished with errors
Messages: 0 fatals / 7 errors / 0 warnings / 0 infos

EPUBCheck completed
```

**Comment by dluschan** [comment]
I've checked this test in ArchLinux and I had same result.
Pay attention, if you don't have epubcheck tool you'll get OK test's result :)

**Comment by blandger** [comment]
You are messing up two issues.
First is test error (an `Err` value: EpubCheck', tests/integration_tests.rs:79)
Second is epub Validating.

**Comment by dluschan** [comment]
I think test output_epub_is_valid failed because ePub file don't validating.
Also I would fix test integration_tests so it fail without epubcheck tool (https://github.com/Michael-F-Bryan/mdbook-epub/pull/81).

**Comment by dluschan** [comment]
Some bugs will be fixed after merging this PR: https://github.com/lise-henry/epub-builder/pull/43

**Comment by blandger** [comment]
There are following issues exist as I think.

1.
Getting correct dummy epub book by running epubcheck command. That is not quite possible, because of stricness epubcheck utility, missing functionality to 'skip' certain errors reported by utility, we have special case for checking which will exist and will be always reported by utility.

2. Turning ON such check makes mdbook-epub build imposible by CI/CD. I doubt that is good thing if we can't skip some errors reported by epubcheck utility.

3. The getting correct epub book used by readers is not the same as getting 'completely clean' epubcheck log for 'test dummy book'. The epubcheck can report many errors but epub book still is correct for many readers.  I see, we have two options - 1) create another 'more correct' test book version and use it inside that integration test with 'epubcheck utility' to run it cleanly without errors, 2) eliminate all errors first (but that is not quite possible, as I wrote before), 3) try to skip certain errors reported by epubcheck.

**Comment by blandger** [comment]
I can assume epubcheck gives 'false positive' check result in our case, so I'm afraid that 'integration test fix' is not acceptable now.

**Comment by dluschan** [comment]
I don't see any problem for fixing epubcheck DummyBook.epub problems and suggest:
1. Publish patch fixed id problem on the crates.io, see [issue](https://github.com/lise-henry/epub-builder/issues/45)
2. Fix problem with duplication file after `additional-resources = ["assets/rust-logo.png"]` in `dummy/book.toml`.
We can append additional check to code or remove this unnecessary line from `dummy/book.toml`. What did you mean when added this line [here]( https://github.com/Michael-F-Bryan/mdbook-epub/pull/73/files#diff-df9e5aa80d8eb967e15a7d25e3f2ae2d2a2b12b8af8d6a8ecd04a291a43cd969)?
3. Fix path to image outside of src directory `![Image](../third_party/wikimedia/Epub_logo_color.svg)`. We can rewrite `find` function:
```
    _ => {
        // skip incorrect resource/image link outside of book /SRC/ folder
        warn!("Sorry, we can't add 'Local asset' that is outside of book's /src/ folder, {:?}", &asset);
    }
```
or move file into src directory or remove it. This is your mentioned [commit]( https://github.com/Michael-F-Bryan/mdbook-epub/pull/73/files#diff-df9e5aa80d8eb967e15a7d25e3f2ae2d2a2b12b8af8d6a8ecd04a291a43cd969) too.
4. Move `<img>` raw tag into `<p>` tag.
My [PR](https://github.com/Michael-F-Bryan/mdbook-epub/pull/89) covers 2-4 items.

**Comment by blandger** [comment]
1. Ok
2. additional-resources = ["assets/rust-logo.png"] Previous utility couldn't gather resources from MD content, so some of them have been added 'manually'. Now we have resource gathering code and 'additional-resources' is not needed in most cases. So that is ok to remove it and prevent 'duplicated resource' in epub.
3. Scenario with updating original MD source (fix the resource link content) is bad. Moving target file into /src/ folder is also bad varian (becase of necessity change MD content). We have an ulituty for epub creation, not a sort of 'MD editor'. But that case is needed to see correct source processing. Probably I will create separate unit/integ. test for that case.
4. Ok
