### ISSUE TITLE
Rust Programming language book doesnt convert to epub as expected

### ISSUE THREAD

**Issue by smithshelke** [Michael-F-Bryan/mdbook-epub#83]
1. Css seems to be a bit broken for fenced codeblocks
2. Doesnt support javascript used by the RPL book to add Ferris in the codeblocks

**Comment by blandger** [comment]
Rename extension from zip into epub.

[The Rust Programming Language-en-0.0.1.zip](https://github.com/Michael-F-Bryan/mdbook-epub/files/13057807/The.Rust.Programming.Language-en-0.0.1.zip)

I've built version from the official repo (my fork) on linux.

One step is needed only... add 
[output.epub]
into book.toml

and run like that (I prefer see logs, put your )
> RUST_LOG=info /rust_projects/mdbook-epub-blandger/target/debug/mdbook-epub /media/book/rust-book-eng

Only one issue can happen on some epub readers.... There is rare comment in MD files like that one:
```
< ! -- manual-regeneration
cd listings/ch11-writing-automated-tests
rm -rf listing-11-01
cargo new listing-11-01 --lib --name adder
cd listing-11-01
cargo test
git co output.txt
cd ../../..
-- >
```
example in file = src/ch11-01-writing-tests.md

It makes some readers "unhappy" because of "double dush" inside mutli-line comment.

**Comment by blandger** [comment]
Rename extension from zip into epub.

[The Rust Programming Language-en-0.0.1.zip](https://github.com/Michael-F-Bryan/mdbook-epub/files/13057807/The.Rust.Programming.Language-en-0.0.1.zip)

I've built version from the official repo (my fork) on linux.

One step is needed only... add 
[output.epub]
into book.toml

and run like that (I prefer see logs, put your )
> RUST_LOG=info /rust_projects/mdbook-epub-blandger/target/debug/mdbook-epub /media/book/rust-book-eng

Only one issue can happen on some epub readers.... There is rare comment in MD files like that one:
```
< ! -- manual-regeneration
cd listings/ch11-writing-automated-tests
rm -rf listing-11-01
cargo new listing-11-01 --lib --name adder
cd listing-11-01
cargo test
git co output.txt
cd ../../..
-- >
```
example in file = src/ch11-01-writing-tests.md

It makes some readers "unhappy" because of "double dush" inside mutli-line comment.

**Comment by blandger** [comment]
> 2\. Doesnt support javascript used by the RPL book to add Ferris in the codeblocks

An epub can't run JS code on page because it doesn't have js engine inside.

Can you give your log file on run ?? Or what the issue do you see locally or using your book ?
