### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by bridgeQiao** [Michael-F-Bryan/mdbook-epub#9]
Hello, I just encountered an error when I install it:

```bash
error[E0616]: field `sections` of struct `mdbook::book::Book` is private
  --> .cargo/git/checkouts/mdbook-epub-bd1aa49df9dbc8c0/2d567f4/src/generator.rs:71:22
   |
71 |         for item in &self.ctx.book.sections {
   |                      ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

I use rustc 1.23.0 in Ubuntu 16.04. What should I do? Thanks!

**Comment by Michael-F-Bryan** [comment]
In rust-lang-nursery/mdBook#564 we made a `Book`'s `sections` field private and replaced it with an `iter()` method. I've updated the `mdbook` dependency and pinned it to a specific commit, when the next `mdbook` release comes around (probably tonight) I'll be able to use the `mdbook` on crates.io instead of pulling it directly from `master`.
